sbatch_config:
  nodes: 1
  gpus: 4
  account: laionize
  time: "00:10:00"
  ntasks_per_node: 1 # generally prefer clip_benchmark distributed
  cpus_per_task: 6
  partition: booster
  output: "slurm_logs/slurm-%A_%a.out"
  job_name: scaling2
  jobs_at_once: 4 # even if the array has more, no more than jobs_at_once will be started
  experiments_list_file_path: "./experiments/val_experiments_list.txt"
  sbatch_script_file_path: "./sbatch_scripts/val_experiment_sbatch_script.sbatch"
  extra_preamble: # this strings will get copied in the sbatch scripts as they are
    - eval "$(/p/home/jusers/puccetti1/juwels/puccetti1/miniconda3/bin/conda shell.bash hook)" # init conda
    - conda activate open_clip
    - export CUDA_VISIBLE_DEVICES="0,1,2,3"
    - echo $SLURM_ARRAY_TASK_ID

datasets:
  -
    task: "zeroshot_retrieval"
    data_name: "mscoco_captions"
    data_path: "/p/home/jusers/puccetti1/juwels/puccetti1/open_clip/data/coco_data_2014"
    distributed: true

models:
  -
    model_name: "mammut_ViT-B-32"
    pretrained_path: "/p/home/jusers/puccetti1/juwels/open_clip_models/finished_runs/mammut_13B_datacomp/checkpoints/epoch_97.pt"
    logs: validation_results/mammut_13B_datacomp
    batch_size: 256
    stage: validation
    extra_args:
      - "--recall_k 1 5"
  -
    model_name: "mammut_ViT-B-32"
    pretrained_path: "/p/home/jusers/puccetti1/juwels/open_clip_models/finished_runs/mammut_64_nodes/checkpoints/epoch_97.pt"
    batch_size: 256
    logs: validation_results/mammut_64_nodes
    stage: validation
    extra_args:
      - "--recall_k 1 5"
  -
    model_name: "mammut_ViT-B-32"
    pretrained_path: "/p/home/jusers/puccetti1/juwels/open_clip_models/finished_runs/2023_08_12-09_27_30-model_mammut_ViT-B-32-lr_0.0009-b_352-j_4-p_amp_bfloat16/checkpoints/epoch_97.pt"
    batch_size: 256
    logs: "validation_results/2023_08_12-09_27_30-model_mammut_ViT-B-32-lr_0.0009-b_352-j_4-p_amp_bfloat16"
    stage: validation
    extra_args:
      - "--recall_k 1 5"
  -
    model_name: "mammut_ViT-B-32"
    pretrained_path: "/p/home/jusers/puccetti1/juwels/open_clip_models/finished_runs/2023_08_09-11_22_39-model_mammut_ViT-B-32-lr_0.0005-b_352-j_4-p_amp_bfloat16/checkpoints/epoch_97.pt"
    batch_size: 256
    logs: "validation_results/2023_08_09-11_22_39-model_mammut_ViT-B-32-lr_0.0005-b_352-j_4-p_amp_bfloat16"
    stage: validation
    extra_args:
      - "--recall_k 1 5"